spring:
  application:
    name: day3

  datasource:
    password: 1
    url: jdbc:postgresql://localhost:2222/postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true

#  web:
#    resources:
#      static-locations: classpath:/resources/images


server:
  port: 4040

#OAuth2

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/auth/realms/SpringBootKeycloak
keycloak:
  auth-server-url: http://localhost:8082/auth
  realm: SpringBootKeycloak
  resource: SpringBootClientId
  public-client: true
  principal-attribute: preferred_username
