insert into address (street, zip, city) values ('4th ST', '52557', 'Fairfield')
insert into address (street, zip, city) values ('14th ST', '52558', 'New Jersey')
insert into category(name) values ('Phone')
insert into category(name) values ('Laptop')
insert into product (name, price, rating, category_id) values ('Iphone 14 Pro Max', 1450, 4, 1)
insert into product (name, price, rating, category_id) values ('Xiaomi POCO 4', 450, 2, 1)
insert into product (name, price, rating, category_id) values ('Laptop Lenovo 16GB RAM', 1800, 3, 2)
insert into product (name, price, rating, category_id) values ('MacBook Pro 32GB RAM', 2100, 5, 2)
insert into user_(email, password, first_name, last_name, address_id) values ('ralphemail@email.com', 'pass123', 'Ralph Winner', 'Deus', 1)
insert into user_(email, password, first_name, last_name, address_id) values ('ralphemail2@email.com', 'pass123', 'Harry', 'Maguire', 2)
insert into review (comment, product_id, user_id) values ('Good', 1, 1)
insert into review (comment, product_id, user_id) values ('Bad', 2, 1)
insert into review (comment, product_id, user_id) values ('Good', 3, 1)
insert into review (comment, product_id, user_id) values ('Bad', 1, 2)
insert into review (comment, product_id, user_id) values ('Good', 2, 2)
insert into review (comment, product_id, user_id) values ('Good', 3, 2)